## Calibrando Frijol en DSSAT 

[Patricia Alvarez](mailto:p.alvarez@cgiar.org), [Alejandra Esquivel](https://github.com/aesquivel94), [Jeison Mesa](https://github.com/Jeikosd), [Jose Luis Cabrera Vega](mailto:jose.cabrera.vega@correounivalle.edu.co)

# Plan de trabajo

Como proceso de calibración, en primera instancia deseamos conocer la incertidumbre y sensibilidad asociada a los parametros de entrada del modelo los cuales son:

-------------------------------------------------------------------
 coeficiente                info                min    max     by  
------------- -------------------------------- ------ ------ ------
    EM-FL          Emergencia a floración        18     36     1   

    FL-SH      tiempo primera flor a primera     1      8      1   
                           vaina                                   

    FL-SD      tiempo primera flor a primera     6      18     1   
                          semilla                                  

    SD-PM      tiempo entre primera semilla y    8      26     1   
                    madurez fisiológica                            

    FL-LF        tiempo primera flor a fin       7      26     1   
                       expansion hoja                              

    LFMAX       tasa máxima de fotosíntesis     0.7    1.6    0.02 

    SLAVR          área foliar específica       220    365     5   

    SIZLF        maximo tamaño de full leaf     116    182     6   

    WTPSD         máximo peso por semilla       0.15   0.65   0.05 

    SFDUR      duración del llenado de grano     11     24     1   
                    por cohorte de vaina                           

    SDPDV        promedio semilla por vaina      1      7      1   

    PODUR        tiempo requerido cultivar       7      16     1   
                        alcance pod                                
-------------------------------------------------------------------

Table: Logical Operators

- Realizar prueba de medias y varianza para determinar al menos en los dos momentos de la funcion de distribucion (proceso en media y varianza )si existen diferencas en rendmiento para cada una de las variables que se ajustan para el proceso de simulacion.

- El anterior paso debe excluir al menos aquellos factores (EM_FL, 16, ....., 26) donde no se necesario graficar la distribuicion asociada a ella. (ANOVA?)

- Analisis Facotorial? utilizando STATIS.

- Analisis grafico de aquellas variables que resultaron relevantes (que en su efecto son sensibles)

