library(tidyverse)
library(stringr)
library(magrittr)
library(data.table)
library(doFuture)

source("make_cultivar.R")
source("write_cul.R")
source("main_functions.R")
source("run_dssat.R")

## Configuracion

dir_run <- "Runs/"
dir_experiment <- "data/Experiment_data/Palmira/"
# id_run <- 2  # to run in a particular .CUL (generated by runif)
dir_dssat <- 'C:/DSSAT46/'
dir_coef <- 'data/rangos_coeficientes.csv'
cultivar <- 'IB0035'
model <- 'CRGRO046'
random_cul = NULL ## parameters to simulate in DSSAT
n_cores <- 2
n <- 10   # number of simulations (remember it is using runif values)

registerDoFuture()
plan(cluster, workers = n_cores)

dssat_sim <- run_mult_dssat()


write_csv(dssat_sim$runs, paste0('outputs/', basename(dir_experiment), "_sim.csv"))
# write_csv(dssat_sim$, paste0('outputs/', basename(dir_experiment), "_sim.csv"))
