

library(tidyverse)
library(stringr)
library(magrittr)
library(data.table)

source("make_cultivar.R")
source("write_cul.R")
source("main_functions.R")


# dir_run <- "Runs/"
# dir_experiment <- "data/Experiment_data/Palmira/"
# id_run <- 1  # to run in a particular .CUL (generated by runif)
# dir_dssat <- 'C:/DSSAT46/'
# dir_coef <- 'data/rangos_coeficientes.csv'
# cultivar <- 'IB0035'
# model <- 'CRGRO046'
# random_cul = NULL ## parameters to simulate in DSSAT

run_dssat <- function(dir_experiment, dir_dssat, dir_coef, cultivar, model, dir_run, id_run, random_cul = NULL){
  
  # dir_base <- paste0(dir_run, id_run)
  
  # make folder to run
  
  dir_run_id <- make_id_run(dir_run, id_run)
  
  # copy files necessary to run
  
  files_running <- files_dssat(dir_dssat, dir_experiment, dir_run_id)
  
  # make_cultivar
  if(is.null(random_cul)){
    
    
   
    random_cul <- make_combination(file = paste0(dir_experiment,  files_running$file_CUL), 
                                   inputs_df = suppressMessages(suppressWarnings(read_csv(dir_coef))) , 
                                   cultivar, 
                                   k = 1) 
    
    # write cultivar
    
    write_cul(random_cul$Cul_parameters, out_dir = dir_run_id)
   
    
  }else{
    
    Cul_parameters <- random_cul$Cul_parameters %>%
      filter(row_number()== id_run)
    
    # write cultivar
    
    write_cul(Cul_parameters, out_dir = dir_run_id)
  }

  
  # read the treatments to run
  
  number_TN <- read_treatments(paste0(dir_run_id, '/', files_running$x_file))
    
  # read region running
  region <- read_region(file = paste0(dir_run_id, '/', files_running$x_file))
  
  
    
  # make batch file
  
  CSMbatch(crop = "BEAN", name = files_running$x_file, filename = paste0(dir_run_id, "/DSSBatch.v46"), 
           number_TN)
  
  ## run
  
  execute_dssat(dir_run_id, model)
  
  # load the information Evaluate.OUT
  evaluate <- read_evaluate(file = paste0(dir_run_id, '/Evaluate.OUT'))
  
  ## select HWAMS ADAPS MDAPS  CWAMS
  ## them it is possible to select other group of variables
  evaluate <- evaluate %>%
    select(HWAMS, ADAPS, MDAPS,  CWAMS)
  
  
  ## HWAH yield
  summary <- read_summary(file = paste0(dir_run_id, '/Summary.OUT')) %>%
    select(PDAT) # for now we select this variables to joint with evaluate
    
  
  coef_random <- magrittr::extract2(random_cul, 2) # select the random coefficients
  
  x <- bind_cols(summary, evaluate)  # joint random coefficients with evaluate information
  
  
  run <- cbind(x,  coef_random, row.names = NULL) %>% ## dataframe of coeffcients and variables of response
            tbl_df() %>%
            mutate(id_run = rep(id_run, nrow(.)), region = rep(region, nrow(.))) %>%
            select(id_run, region, everything())
  
  return(list(runs = run, coef_random = coef_random))
  
  
 
  
  
}

run_dssat(dir_experiment, dir_dssat, dir_coef, cultivar, model, dir_run, 1, random_cul = NULL)


