# dir_run <- "Runs/"
# dir_experiment <- "data/Experiment_data/Palmira/"
# id_run <- 1  # to run in a particular .CUL (generated by runif)
# dir_dssat <- 'C:/DSSAT46/'
# dir_coef <- 'data/rangos_coeficientes.csv'
# cultivar <- 'IB0035'
# model <- 'CRGRO046'

run_dssat <- function(dir_experiment, dir_dssat, dir_coef, cultivar, model, dir_run, id_run){
  
  # dir_base <- paste0(dir_run, id_run)
  
  # make folder to run
  
  dir_run_id <- make_id_run(dir_run, id_run)
  
  # copy files necessary to run
  
  files_running <- files_dssat(dir_dssat, dir_experiment, dir_run_id)
  
  # make_cultivar
  random_cul <- make_combination(file = paste0(dir_experiment,  files_running$file_CUL), 
                                 inputs_df = read_csv(dir_coef), 
                                 cultivar, 
                                 k = 1) 
  
  # write cultivar
  
  write_cul(random_cul, out_dir = dir_run_id)
  
  
  # make batch file
  
  CSMbatch(crop = "BEAN", name = files_running$x_file, filename = paste0(dir_run_id, "/DSSBatch.v46"))
  
  ## run
  
  execute_dssat(dir_run_id, model)
  
  # load the information Evaluate.OUT
  evaluate <- read_evaluate(file = paste0(dir_run_id, '/Evaluate.OUT'))
  
  ## HWAH yield
  summary <- read_summary(file = paste0(dir_run_id, '/Summary.OUT')) 
    
  # por ahora retornemos los coeficientes y el rendimiento.

 
  
  
}